sudo: required

env:
  matrix:
    - IMG=ubuntu:18.04
    - IMG=ubuntu:19.04
    - IMG=ubuntu:19.10
    - IMG=ubuntu:20.04
    - IMG=debian:stable
    - IMG=debian:unstable
    - IMG=debian:testing

services:
 - docker

script:
  - docker build --build-arg "IMG" "."
